### ISSUE TITLE
missing file: importance_teacher_weights.pt

### ISSUE THREAD

**Issue by chongjg** [lbaermann/qaego4d#2]
Hi there,
It seems that the `"../22_04_b5aa4428_0/importance_teacher_weights.pt"` file cannot be found.
Could you please provide it or tell me how to get it?
Thanks in advance!

**Comment by lbaermann** [comment]
Hi chongjg,

you only need that file in case you actually want to train the rehearsal memory model (`model: rehearsal_mem` in `config/base.yaml`). To create it, you first need to train with `model: importance_teacher`, then run `python -m model.importance_teacher --output_file importance_teacher_weights.pt  --checkpoint_path path/to/checkpoint/of/previous/training.pt`, and finally adapt the `config/model/rehearsal_mem.yaml` to point to the correct importance teacher weights file. With this process, the RM model can pick meaningful segments to attend to, as the attention scores of the unconstrained importance teacher model are used for supervision.

If you configure any other model, such two-step process is not needed.
