### ISSUE TITLE
videoUid doesn't match in answers.json and ego4d,json (from ego4d downloading)

### ISSUE THREAD

**Issue by Deaddawn** [lbaermann/qaego4d#3]
Hi, I tried to use videouid in answers.json to match the one  in ego4d,json but failed, any idea why?

**Comment by lbaermann** [comment]
For future reference:
The `video_id` field actually refers to the Ego4D clips (not full scale videos). E.g., the video id `75d3fc52-3776-47d4-b7fd-8074d30b06d1` refers to the Ego4D file `v1/clips/75d3fc52-3776-47d4-b7fd-8074d30b06d1.mp4`
