### ISSUE TITLE
what does moment_start_frame mean

### ISSUE THREAD

**Issue by Deaddawn** [lbaermann/qaego4d#4]
I found that the moment_start_frame in annontaions doesn't match the original MP4 video, how do you calculate that?

**Comment by lbaermann** [comment]
Hi, these values are calculated directly from the annotations provided by the underlying Ego4D NLQ set: 
https://github.com/lbaermann/qaego4d/blob/bc1e29d3138a7db4ba35e19d9c1f05302e0c34c3/tools/create_pure_videoqa_json.py#L31

**Comment by Deaddawn** [comment]
thx
