### ISSUE TITLE
Try to use eval.py

### ISSUE THREAD

**Issue by Deaddawn** [lbaermann/qaego4d#5]
Hi, I am trying to use eval.py, for gold_answers and eval_file, I pass answers.json for a test, but got this error:

    raise TypeError(f'{prefix}: {err_msg}')
TypeError: BLEU: `refs` should be a sequence of sequence of strings.

**Comment by Deaddawn** [comment]
> Hi, I am trying to use eval.py, for gold_answers and eval_file, I pass answers.json for a test, but got this error:
> 
> ```
> raise TypeError(f'{prefix}: {err_msg}')
> ```
> 
> TypeError: BLEU: `refs` should be a sequence of sequence of strings.

A lot of bugs going on here, suggest take a look

**Comment by lbaermann** [comment]
If you take a look at https://github.com/lbaermann/qaego4d/blob/bc1e29d3138a7db4ba35e19d9c1f05302e0c34c3/eval/eval.py#L123 how the answers json file is handled, the script directly expects a mapping from sample id to answer. So you need to extract one of the split dictionaries (train, val, test) in the file `answers.json` as provided in the dataset, or you "flatten" that file to contain all samples from all splits at once.

If this does not help, can you provide more details (stack trace, input etc)?
