### ISSUE TITLE
BLEU used in paper, is it BLEU-4?

### ISSUE THREAD

**Issue by Deaddawn** [lbaermann/qaego4d#6]

**Comment by lbaermann** [comment]
Yes, it is BLEU-4, as written in the last sentence of Section 6.1.

**Comment by Deaddawn** [comment]
Thanks, not paying attention,my bad.



---- Replied Message ----
| From | ***@***.***> |
| Date | 06/04/2024 21:39 |
| To | ***@***.***> |
| Cc | ZD ***@***.***>***@***.***> |
| Subject | Re: [lbaermann/qaego4d] BLEU used in paper, is it BLEU-4? (Issue #6) |

Yes, it is BLEU-4, as written in the last sentence of Section 6.1.
