### ISSUE TITLE
Request for pth file

### ISSUE THREAD

**Issue by Shrad1234** [lbaermann/qaego4d#7]
Dear authors,

I am currently working on a research project focused on robotics and social companion robots for the elderly and individuals with memory disorders. I would greatly appreciate it if you could provide me with the trained .pth file for testing purposes. It would be incredibly helpful.

Thank you.

**Comment by lbaermann** [comment]
Hi, 

which models do you need exactly? Please contact me via mail (it's in the paper).

Best,
Leonard

**Comment by Shrad1234** [comment]
I actually sent you a mail from ***@***.*** and
***@***.*** but was not sure whether you received it
